### ISSUE TITLE
Hide in settings

### ISSUE THREAD

**Issue by upulw2020** [OpenArchive/save-android#49]
Settings
Hide Metadata/Proofmode
Hide Security/Tor
Hide Healthchecks

**Comment by upulw2020** [comment]
@rapuckett the settings screen is a little messed up
![Image](https://github.com/user-attachments/assets/83c2cef6-faa4-4721-85b4-9e0f482c0eff)

**Comment by rapuckett** [comment]
![Image](https://github.com/user-attachments/assets/e844f1c3-a22a-4bd7-bd40-ec3b34dbe8cb)
